### ISSUE TITLE
1.13 versions don't download 1.13.jar

### ISSUE THREAD

**Issue by anonymousAwesome** [ammarx/TagLauncher_3#3]
I ran the file downloader on versions 1.13 and 1.13-pre1.  Both versions claimed to have installed correctly, but when I tried to run them I got the error `java.lang.NullPointerException` in the console log and the program claimed the installation was corrupted.  1.12.2 installed correctly, and I noticed that the versions/1.12.2 folder contained the file 1.12.2.jar while the 1.13 versions did not.  On a hunch I downloaded the 1.13 client jar from https://mcversions.net/, renamed it 1.13.jar, and placed it in the 1.13 folder and the program worked.

**Comment by ammarx** [comment]
Thank you for the feedback. An update to the API will be coming shortly to fix this.

**Comment by ammarx** [comment]
Fixed. Thanks.
https://github.com/ammarx/TagLauncher_3/releases/tag/1.40
